#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html
#echo 'Hello World!'  > /var/www/html/index.html

#testing nginx 
sudo nginx -t 

#Reloading nginx
sudo service nginx reload
